### ISSUE TITLE
[Feature Request]: How to specify cookie_file and key_file in rookie?

### ISSUE THREAD

**Issue by bsll0828** [thewh1teagle/rookie#12]
### Describe the feature

How to specify cookie_file, key_file and domain_name in Rookie,
In browser_cookie3 I can do that like this: 
browser_cookie3.any_browser(cookie_file='something', domain_name="something", key_file='something'), 
but in rookie it doesn't work.

**Comment by thewh1teagle** [comment]
Hi
It's no possible with `Python`, but possible with `Rust` and with the `CLI` tool (See the readme)
I can add it to Python too if you're interested

**Comment by thewh1teagle** [comment]
Added to latest version of rookiepy
Install with
```shell
pip install -U rookiepy
```
Use with
```python
import rookiepy

db_path = r"C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\default\network\Cookies"
key_path = r"C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Local State" # optional
cookies = rookiepy.any_browser(db_path=db_path, key_path=key_path, domains=None)
print(cookies)
```

**Comment by thewh1teagle** [comment]
Added also to examples
[examples/custom_path.py](https://github.com/thewh1teagle/rookie/blob/main/examples/custom_path.py)

**Comment by bsll0828** [comment]
cooooool, you helped me!
