### ISSUE TITLE
[Bug]: panicked at macos

### ISSUE THREAD

**Issue by daoxiaonoodles** [thewh1teagle/rookie#15]
### What happened?

RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/cookie_helper`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: decrypt_encrypted_value failed', src/main.rs:5:56
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1076:23
   4: cookie_helper::main
             at ./src/main.rs:5:32
   5: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

### Steps to reproduce

use rookie::{self, common::enums::Cookie};

fn main() {
    let domains = Some(vec!["google.com"]); // set to None to get all
    let cookies: Vec<Cookie> = rookie::chrome(domains).unwrap();
    println!("{cookies:?}");
}
1.cargo run

### What browsers are you seeing the problem on?

Chrome

**Comment by thewh1teagle** [comment]
Thanks for reporting!
Can you try with safari or other browsers and let me know if them works?

**Comment by daoxiaonoodles** [comment]
> Thanks for reporting! Can you try with safari or other browsers and let me know if them works?

yes,I use the Safari and edge browser, and it also returns the same result.

**Comment by thewh1teagle** [comment]
I checked that on `MacOS` version `13.5` with `M1`
`Safari` and `Firefox` worked! 
But I can see that `Chrome` based browsers doesn't.
I'll check what cause that, I just need to compare it with `browser_cookie3` because it works there

**Comment by thewh1teagle** [comment]
Fixed in `v0.3.3`
You can install with
```shell
pip3 install -U rookiepy
```
