### ISSUE TITLE
[Bug]: It doesn't work correctly with Octo Browser

### ISSUE THREAD

**Issue by igorank** [thewh1teagle/rookie#16]
### What happened?

Hello, really grateful for your software, it's saved me a lot of time. However, there's a minor issue – it doesn't work properly with Octo Browser (https://octobrowser.net/). I've come up with a quick fix that addresses this problem, but I've never worked with Rust before, and I'd appreciate if you (the author) could resolve this bug related to cookie unloading via Python bindings from Octo Browser. Here's the link to my commit that resolves this issue with Octo Browser (Chromium): https://github.com/igorank/rookie/commit/859f6d7baa361387f940dd47e4385e39ec6d6360

### Steps to reproduce

1. call function: rookiepy.any_browser(db_path=db_path, key_path=key_path, domains=None)
2. Unlocking chrome database, it may take a while (sometimes up to minute)
thread '<unnamed>' panicked at rookie-rs\src\browser\chromium.rs:89:36:
range end index 3 out of range for slice of length 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception in thread Thread-1:
File "C:\Users\work\Documents\Projects\fb-multi-tasker\cookie_manager.py", line 15, in _load_cookies_from_db
    cookies = rookiepy.any_browser(db_path=db_path, key_path=key_path, domains=None)
pyo3_runtime.PanicException: range end index 3 out of range for slice of length 1

### What browsers are you seeing the problem on?

Chromium

### Relevant log output

```shell
Unlocking chrome database, it may take a while (sometimes up to minute)
thread '<unnamed>' panicked at rookie-rs\src\browser\chromium.rs:89:36:
range end index 3 out of range for slice of length 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception in thread Thread-1:
File "C:\Users\work\Documents\Projects\fb-multi-tasker\cookie_manager.py", line 15, in _load_cookies_from_db
    cookies = rookiepy.any_browser(db_path=db_path, key_path=key_path, domains=None)
pyo3_runtime.PanicException: range end index 3 out of range for slice of length 1
```

**Comment by thewh1teagle** [comment]
Thanks, looks like you found the problem!
I will check that

**Comment by thewh1teagle** [comment]
Added to latest version in the repo (not yet released)
you can try it and let me know if it works for you :)

**Comment by igorank** [comment]
> Added to latest version in the repo (not yet released) you can try it and let me know if it works for you :)

Thank you very much, I will definitely try it and let you know :)
