### ISSUE TITLE
[Feature Request]: Windows reading chrome cookies that are currently in use.

### ISSUE THREAD

**Issue by pkptzx** [thewh1teagle/rookie#22]
### Describe the feature

see:
https://github.com/moonD4rk/HackBrowserData/issues/243

https://github.com/Naturehi666/searchall/issues/3 <- it's work

u just use rust implementation.  
and I already found low-level filesystem library implemented in Rust , I'll try it when I'm free.

**Comment by thewh1teagle** [comment]
I see that it uses shadow copy and it works?
