### ISSUE TITLE
[Feature Request]: is there a way to copy user profile of a browser?

### ISSUE THREAD

**Issue by andizaa** [thewh1teagle/rookie#23]
### Describe the feature

instead of only cookies, is there a way to copy user profile of a browser? 
so that I can open a new browser (via selenium) with that profile.

**Comment by thewh1teagle** [comment]
The goal of the library is to find and extract cookies from browsers.
If you need to get the profiles I suggest finding a library or writing simple script and be helped from the file config.rs which have a lot of paths
