### ISSUE TITLE
Can i hide the rust panic message?

### ISSUE THREAD

**Issue by zWolfrost** [thewh1teagle/rookie#28]
Hi, I'm using the python bindings for this library and so far so good, it's great. My only issue is that when I'm calling a method like `opera` when i don't have opera installed it gives out a rust panic exception.
```
thread '<unnamed>' panicked at bindings/python/src/lib.rs:70:42:
called `Result::unwrap()` on an `Err` value: can't find any cookies file
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is alright, given that the browser couldn't be found, the problem is that i can't seem to catch this exception. When this happens this error gets printed out no matter what. I'm just making sure this is to be expected, and if it is, i would really like a way to avoid printing the error.

By the way, I'm using Linux and the library is version 0.4.0

Also sorry for the mess that is this issue, i've been second-guessing myself a lot.

Thanks for your patience.

**Comment by zWolfrost** [comment]
I have read the docs and found the way to disable logging. I'm really sorry for wasting your time.

**Comment by thewh1teagle** [comment]
Hey, thanks for reporting!
rookie use pyo3 to create the python bindings, 
I think that the problem is that I used `unwrap()` in the bindings which leads to rust panic if there's an error, and I should instead return Result type which python should handle better
