### ISSUE TITLE
when getting cookies domain var isn't included in the dict

### ISSUE THREAD

**Issue by MisterChaneb** [thewh1teagle/rookie#3]
as the title says do please include the domain i'm using load function for some reason it's missing the domain variable.

**Comment by thewh1teagle** [comment]
Hi @MisterChaneb 
I already include the domain in the `host` attribute, so instead of using `cookie.domain` you should use `cookie.host`
```python
from rookiepy import load, to_dict
cookies = load()
cookies = to_dict(cookies)
for cookie in cookies:
  print('host: ', cookie['host'])
```

**Comment by MisterChaneb** [comment]
Its not a matter of choice. Playwright requires it.

**Comment by thewh1teagle** [comment]
Show me example code you use to load it, I'm not sure what playwright expecting, so maybe it's not only the host issue but even after I include domain it won't work

**Comment by MisterChaneb** [comment]
No because i added the domain manually it worked? i tested without domain it's just a /
does not work. with a domain i just manually added it and it worked

**Comment by thewh1teagle** [comment]
I changed it in latest version

**Comment by MisterChaneb** [comment]
Thanks a lot mate! I wouldn't mind if you want to have it be host as an argument option for other compatability reasons, otherwise great work.
