### ISSUE TITLE
[Feature Request]: Can you add a function to save cookie as Netscape cookie file format?

### ISSUE THREAD

**Issue by bk111** [thewh1teagle/rookie#34]
### Describe the feature

I will pass the cookie.txt to yt-dlp, the command is "yt-dlp --cookies cookies.txt ”， but it seems it needs Netscape cookie file format.

Can you add a function to save cookie for a domain as Netscape cookie file format?

**Comment by thewh1teagle** [comment]
@bk111 

Sure!
I added support for `NetScape` format in the `Rust` library / `cli` / `python` (But I didn't published yet) 
How do you use it? so I can publish and you can test it
