### ISSUE TITLE
[Feature Request]: Add support for Arc Browser

### ISSUE THREAD

**Issue by techtanic** [thewh1teagle/rookie#35]
### Describe the feature

Browser: https://arc.net/
Its a chromium replacement
Cookies location windows: `%LOCALAPPDATA%\Packages\TheBrowserCompany.Arc_ttt1ap7aakyb4\LocalCache\Local\Arc\User Data\Default\Network`
I think it installs like a UWP, hence its path, the `ttt1ap7aakyb4` might be random. 
And it supports multiple profiles which would be same as other chromium, `Profile *` in place of `Default`.

**Comment by thewh1teagle** [comment]
Hey!
Thanks for the suggestion.
I added it to the latest version
