### ISSUE TITLE
[Feature Request]: Add support for browsers lynx and w3m

### ISSUE THREAD

**Issue by mahlzahn** [thewh1teagle/rookie#42]
### Describe the feature

These are two text-based browsers from 1992 and 1995, which are both still maintained and which run on Linux. Their cookie files are just simple tab-separated text files (but with different specification).

I already implemented this feature for linux in the browser_cookie3 package (although not merged, yet), but this is in python and would need to be translated to proper rust code: https://github.com/borisbabic/browser_cookie3/pull/184. See the proposed changes, there!

The [lynx](https://lynx.invisible-island.net/) cookie file looks like Netscape cookie file but it isn’t. Thus, e.g., the python implementation of `http.cookiejar.MozillaCookieJar` fails on the cookie file. Lynx runs also on Windows, MacOS, BSD, etc.

[W3m](https://github.com/tats/w3m)’s cookie file implementation is here: https://github.com/tats/w3m/blob/master/cookie.c#L472 with the flags defined here: https://github.com/tats/w3m/blob/master/fm.h#L754.

**Comment by thewh1teagle** [comment]
Sounds like very good enhancment for rookie!

> I already implemented this feature for linux in the browser_cookie3 package (although not merged, yet), but this is in python and would need to be translated to proper rust code: [borisbabic/browser_cookie3#184](https://github.com/borisbabic/browser_cookie3/pull/184). See the proposed changes, there!

Did you tested that PR on both browsers?
If so, we can replicate it in Rust into rookie

**Comment by thewh1teagle** [comment]
These browsers rarely used. I tried to use `lynx`. it doesn't even store cookies by default :)
I'll close the issue, if someone Really needs to support that feel free to comment here.
