### ISSUE TITLE
[Feature Request]: Windows cannot import Safari

### ISSUE THREAD

**Issue by JoeanAmier** [thewh1teagle/rookie#45]
### Describe the feature

I know Windows cannot read Safari browser cookies, but my project is cross platform. I want to display all browsers and let users choose the browser. If the corresponding browser does not support the platform, I hope to throw an exception, and then I can capture the exception and prompt the user, instead of being unable to import directly. Currently, the module throws an ImportError directly, which is not suitable for direct capture. Otherwise, it is impossible to determine whether it is a platform issue or if the module is not installed. It is recommended to throw a custom exception.

**Comment by thewh1teagle** [comment]
Hey
I think that it's a Python convention and you should conditionally import different browsers functions per platform.

**Comment by JoeanAmier** [comment]
Just a suggestion, if the user attempts to import an object that is not supported by the platform, the module should directly throw a more appropriate error type EnvironmentError or OSError. Otherwise, the user needs to consult the module's source code to know the reason.

**Comment by FeldrinH** [comment]
I have a similar need and what I settled on is doing something like this:
```python
try:
    browsers.append(rookiepy.safari)
except AttributeError:
    pass # Presumably on a platform that does not have Safari
```

**Comment by JoeanAmier** [comment]
> I have a similar need and what I settled on is doing something like this:
> 
> ```python
> try:
>     browsers.append(rookiepy.safari)
> except AttributeError:
>     pass # Presumably on a platform that does not have Safari
> ```

If the module does not consider throwing more friendly errors, the best solution is to judge the system type like the module, and then import the browser objects supported by the current system.

**Comment by thewh1teagle** [comment]
<img width=300 src="https://github.com/user-attachments/assets/08dcd979-58f1-49a6-b627-7dac01fda9ac">
The error looks to me completely normal. macOS doesn't have internet_explorer so it throws `ImportError`
