### ISSUE TITLE
[Bug]: Python docstring issue

### ISSUE THREAD

**Issue by shner-elmo** [thewh1teagle/rookie#46]
### What happened?

Really cool library overall, but I think I stumbled into a documentation error. 
The arguments don't seem to match with the error.

![image](https://github.com/user-attachments/assets/4fa9d2c2-2c45-420e-9f96-22623f317e23)

Other than that, `rookiepy.chrome(['...'])` and `rookiepy.load(['...'])` are working fine.

Also, is this a feature or a bug lol? (seems like there is not commit hash for this)
![image](https://github.com/user-attachments/assets/ba9fcb22-b75f-4a84-b22c-7f27f3abace7)

### Steps to reproduce

python 3.11.4
rookiepy 0.5.2()
ubuntu

call `rookiepy.any_browser()` and pass a list of strings

**Comment by thewh1teagle** [comment]
Hey!
Thanks for report.
It seems that the type hints are wrong. the function accept more parameters

https://github.com/thewh1teagle/rookie/blob/78c292cafb9d8ecc5a09f093834d3c0a15594866/bindings/node/src/lib.rs#L44-L48

You may want to use instead the function `load()`

**Comment by shner-elmo** [comment]
Got it. Would love to submit a PR with the changes reflecting what is defined in lib.rs
