### ISSUE TITLE
[Bug]: Load doesnt return cookies from all browsers with the domain.

### ISSUE THREAD

**Issue by techtanic** [thewh1teagle/rookie#48]
### What happened?

Python
```rookiepy.load(["www.web.com"])``` returns empty.
Looks like it doesnt check all the browsers, and just return from the first browser it finds. 
Make it  instead get all the supported browsers and find the matching domain cookies from all browser.

Maybe also make it check the default browser first.

### Steps to reproduce

Installed browsers:`firefox, edge, arc`
Only arc has Cookies.
```py
import rookiepy

c1 = len(rookiepy.load(["www.udemy.com"]))
c2 = len(rookiepy.arc(["www.udemy.com"]))

print("Load:", c1)
print("Arc:", c2)

"""Output:
Load: 0
Arc: 29
"""
```

**Comment by thewh1teagle** [comment]
@techtanic 

Thanks for report! I forgot to add arc browser to load function.

https://github.com/thewh1teagle/rookie/blob/main/rookie-rs/src/lib.rs#L368

**Comment by techtanic** [comment]
Ahh makes sense, Would be appreciated of you could push out an update.

**Comment by thewh1teagle** [comment]
Published new version

pip install rookiepy==0.5.3b0

Let me know if it works

**Comment by techtanic** [comment]
It works perfectly! I really appreciate it.
