### ISSUE TITLE
Some cookies are missing(?)

### ISSUE THREAD

**Issue by 5j9** [thewh1teagle/rookie#5]
```python
import browser_cookie3, rookiepy

print(f'{len(rookiepy.firefox())=}')
print(f'{len(browser_cookie3.firefox())=}')

print(len(rookiepy.firefox(['google.com'])))
print(len(browser_cookie3.firefox(domain_name='google.com')))

```

On my Windows 10 system the above scripts prints:
```
len(rookiepy.firefox())=675
len(browser_cookie3.firefox())=7104
47
51
```
Not sure if my method of comparison above is correct, but it looks to me that browser_cookie3 is able to find more cookies.

**Comment by MisterChaneb** [comment]
either cookies are missing or there are dupelicate cookies
is it possible you can check for dupelicates?

**Comment by thewh1teagle** [comment]
@5j9 
You right, some cookies from current session are missing.
but from what you sent something is strange, 
```
len(rookiepy.firefox())=675
len(browser_cookie3.firefox())=7104
```
what's the numbers `675` and `7104`?

**Comment by stappersg** [comment]
> Not sure if my method of comparison above is correct

Me neither.

Idea: Print the cookies names.  With `rookie` and  for comparison with `browser_cookie3`.

**Comment by 5j9** [comment]
> Idea: Print the cookies names. With `rookie` and for comparison with `browser_cookie3`.

Here is another example with names printed:
```python
import browser_cookie3, rookiepy

print('rookiepy:')
for c in rookiepy.firefox(['github.com']):
    print(c.name)

print('\n\nbrowser_cookie3:')
for c in browser_cookie3.firefox(domain_name='github.com'):
    print(c.name)
```
Prints:
```
rookiepy:
_octo
logged_in
_device_id
dotcom_user
fileTreeExpanded
_docs-events
user_session
__Host-user_session_same_site
has_recent_activity


browser_cookie3:
_octo
logged_in
dotcom_user
fileTreeExpanded
color_mode
preferred_color_mode
tz
_device_id
user_session
__Host-user_session_same_site
has_recent_activity
_gh_sess
ignored_unsupported_browser_notice
tz
_docs-events
_csrf
LiSESSIONID
_gh_sess
_helphub_session
state
logged
token
_support_session
```

> what's the numbers `675` and `7104`?

They are the result of python f-string evaluation.
```python
print(f'{1+1=}')
# prints:
# 1+1=2
````

**Comment by thewh1teagle** [comment]
@5j9 
Oh I see, but I'm still not sure how many cookies you have from each function
```
len(rookiepy.firefox())=675 <- this is the len?
len(browser_cookie3.firefox())=7104 <- this is the len?
47 <- what's that?
51 <- what's that?
```

**Comment by 5j9** [comment]
Sorry for the messy example. I should've used the same syntax for all print statements. Basically

* length of `rookiepy.firefox()`  was 675.
* length of `browser_cookie3.firefox()`  was 7104.

* length of `rookiepy.firefox(['google.com']))` was 47.
* length of `rookiepy.firefox(['google.com']))` was 51.

**Comment by thewh1teagle** [comment]
Thanks.
I'm working on adding session cookies to rookie in firefox as well.
in the meanwhile, if it's possible for you to check again the length with little modification in browser_cookie3 it would be great.

1. Navigate to the browser_cookie3 folder (just click some function in your `ide` it should go there)
2. and then change here:

[`browser_cookie3/__init__.py` LINE 980](https://github.com/borisbabic/browser_cookie3/blob/master/browser_cookie3/__init__.py#L980)
[`browser_cookie3/__init__.py` LINE 980](https://github.com/borisbabic/browser_cookie3/blob/master/browser_cookie3/__init__.py#L981)
just comment out both in your library which you installed on your `PC`, and check again the lengths to see if it's the same as from `rookiepy`

**Comment by 5j9** [comment]
> comment out both in your library which you installed on your `PC`, and check again the lengths to see if it's the same as from `rookiepy`

After the change the difference is almost gone (actually rookiepy is showing a few more cookies this time):

* length of `rookiepy.firefox()`  was 668.
* length of `browser_cookie3.firefox()`  was 587.
* length of `rookiepy.firefox(['google.com'])` was 47.
* length of `browser_cookie3.firefox(domain_name='google.com')` was
43.

**Comment by thewh1teagle** [comment]
Thanks for checking, that means it probably the reason,
I published new version which takes session cookies as well :)
You can update it with
`pip install -U rookiepy`

**Comment by 5j9** [comment]
Great!

With the version 0.2.5 installed:
```
* length of `rookiepy.firefox()`  was 7401.
* length of `browser_cookie3.firefox()`  was 7096.

* length of `rookiepy.firefox(['google.com'])` was 6779.
* length of `browser_cookie3.firefox(domain_name='google.com')` was 50.
```
Note that now specifying domains seems have lost its filtering effect and `rookiepy.firefox(['google.com'])` returns an usually hight number of cookies.
