### ISSUE TITLE
[Feature Request]: Zen Browser Support [Firefox Port]

### ISSUE THREAD

**Issue by techtanic** [thewh1teagle/rookie#52]
### Describe the feature

https://zen-browser.app/

Its a Firefox port so it should be similar

Root Directory: ```%APPDATA%\zen\Profiles\vt4nhhy.Default (alpha)```
Local Directory: ```%LOCALAPPDATA%\zen\Profiles\vt4nhhy.Default (alpha)```

Really appreciate your work.

**Comment by thewh1teagle** [comment]
Added in v0.5.6
