### ISSUE TITLE
[Feature Request]: Show Passwords as well

### ISSUE THREAD

**Issue by SomePersonOk** [thewh1teagle/rookie#70]
### Describe the feature

hey thank you for your fast lighweight code.
there is a few suggestions:

i can't see any options that would show cookies for each profile. i guess it would be really helpful if the app would get the cookies for each profile of each browser and the seperates them since having them all together would defenitly be unsuable and cause a lot of problems as if i try to load them to my browser there is cookies for one user and then another... and then from other browsers... all in one file and i can't tell which is which and whom is whom.
so it would be a lot nicer if all browsers would be saved in each file where the exe is executed and each profile in its own folder.

also since you already have the encyption keys and you have all the paths why not to get the passwords as well?
it would be alot more complete if we could also get the passwords as well and it wouldn't be needed for another app to do the password part.

and again thanks for the efforts.

**Comment by thewh1teagle** [comment]
Rookie created only for extract cookies. 
You can use [HackBrowserData](https://github.com/moonD4rk/HackBrowserData) instead.
