### ISSUE TITLE
[Bug]: Custom path fails

### ISSUE THREAD

**Issue by SomePersonOk** [thewh1teagle/rookie#71]
### What happened?

Custom path doesn't work and throws error, while using rookiepy.chrome() works fine

### Steps to reproduce

here's the code i used for the output above:

```
for profile in profile_list:
        try:
            cookie_db = os.path.join(chrome_path, profile, 'Network', 'Cookies')
            print(cookie_db)
            cookiesdic = rookiepy.any_browser(db_path=cookie_db)
```

### Relevant log output

```shell
C:\Users\rdayy\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies
Can't find any cookies

Location:
    rookie-rs\src/lib.rs:475:3
```

**Comment by SomePersonOk** [comment]
, domains=None

**Comment by thewh1teagle** [comment]
Fixed in https://github.com/thewh1teagle/rookie/issues/75
See the commit there. there error should tell why it happens.

**Comment by SomePersonOk** [comment]
tried the latest update and i still got the same error,
i changed from os.path to pathlib.Path and it worked. that's weird because it only works with pathlib and even if i give it the same value i get from pathlib as string it still wouldn't work
